name: ğŸš€ Build and deploy to acr

on:
  push:
    branches: ["feature/acr-deployment"]

env:
  WORKING_DIR: users-management

permissions:
  contents: read
  packages: write
  actions: read

jobs:
  setup:
    runs-on: "ubuntu-latest"
    outputs:
      MATRIX: ${{ env.WORKING_DIR }}

    steps:
      - name: ğŸ“‚ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branchName }}

      - name: ğŸ› ï¸ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

  build-and-deploy:
    runs-on: "ubuntu-latest"
    needs: setup
    strategy:
      matrix:
        directory: ${{ fromJson(needs.setup.outputs.MATRIX) }}

    steps:
      - name: ğŸ“‚ Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branchName }}

      - name: ğŸ”‘ Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ğŸ—ï¸ Login to Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZ_USERNAME }}
          password: ${{ secrets.AZ_PASSWORD }}

      - name: ğŸšš Change Path Matrix Directory
        run: |
          CUSTOM_MATRIX_DIRECTORY=$(echo "${{ matrix.directory }}" | sed 's/\//./g')
          echo "CUSTOM_MATRIX_DIRECTORY=$CUSTOM_MATRIX_DIRECTORY" >> "$GITHUB_ENV"

      # - name: ğŸ‘· Import Function App Version
      #   run: |
      #     version=$(python -c "import ${{ env.CUSTOM_MATRIX_DIRECTORY }}.project; print(${{ env.CUSTOM_MATRIX_DIRECTORY }}.project.__version__)")
      #     echo "TAG=$version" >> "$GITHUB_ENV"  

      - name: ğŸ—ï¸ Build and push Docker image to Azure Container Registry
        run: |
          az acr build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ matrix.directory }}:0.0.1 -r ${{ secrets.REGISTRY_LOGIN_SERVER }} ./${{ matrix.directory }}




